# Generated by Django 5.0.1 on 2024-04-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='cpf',
            new_name='st_cpf_cnpj',
        ),
        migrations.RenameField(
            model_name='socio',
            old_name='nome',
            new_name='st_nome',
        ),
        migrations.AlterModelTable(
            name='socio',
            table='cnpj_tb_socio',
        ),
    ]
