# Generated by Django 5.0.1 on 2024-09-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='busca',
            table=None,
        ),
    ]
