# Generated by Django 5.0.1 on 2024-04-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0002_rename_cpf_socio_st_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socio',
            options={'managed': False},
        ),
    ]
