# Generated by Django 5.0.1 on 2024-04-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0003_alter_socio_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='socio',
            table='cnpj.tb_socio',
        ),
    ]
