# Generated by Django 5.0.1 on 2024-04-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0004_alter_socio_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='socio',
            table='tb_socio',
        ),
    ]
