# Generated by Django 5.0.1 on 2024-04-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0005_alter_socio_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('cnpj_base', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=50, null=True)),
                ('cd_motivo_situacao_cadastral', models.CharField(blank=True, max_length=10, null=True)),
                ('cd_cnae_principal', models.CharField(blank=True, max_length=10, null=True)),
                ('dt_inicio_atividade', models.DateField(blank=True, null=True)),
                ('st_uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
