# Generated by Django 5.0.1 on 2024-04-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0006_busca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_cnae', models.CharField(max_length=255)),
                ('st_cnae', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_cnae',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituacaoCadastral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_motivo_situacao_cadastral', models.CharField(max_length=255)),
                ('st_motivo_situacao_cadastral', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_motivo_situacao_cadastral',
                'managed': False,
            },
        ),
    ]
