# Generated by Django 5.0.1 on 2024-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0007_cnae_situacaocadastral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busca',
            name='cd_cnae_principal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='busca',
            name='cd_motivo_situacao_cadastral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
