# Generated by Django 5.0.1 on 2024-04-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0008_alter_busca_cd_cnae_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_nome_fantasia', models.CharField(blank=True, max_length=200, null=True)),
                ('st_cnpj_base', models.CharField(max_length=20)),
                ('cd_motivo_situacao_cadastral', models.CharField(blank=True, max_length=50, null=True)),
                ('cd_cnae_principal', models.CharField(blank=True, max_length=50, null=True)),
                ('dt_inicio_atividade', models.DateField(blank=True, null=True)),
                ('st_uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
