# Generated by Django 5.0.1 on 2024-04-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0009_estabelecimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estabelecimento',
            options={'managed': False},
        ),
    ]
