# Generated by Django 5.0.1 on 2024-04-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0010_alter_estabelecimento_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estabelecimento',
            table='tb_estabelecimento',
        ),
    ]
