# Generated by Django 5.0.1 on 2024-04-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0011_alter_estabelecimento_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busca',
            name='dt_inicio_atividade',
            field=models.CharField(blank=True, null=True),
        ),
    ]
