# Generated by Django 5.0.1 on 2024-07-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0012_alter_busca_dt_inicio_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_razao_social', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tb_empresa',
                'managed': False,
            },
        ),
    ]
