# Generated by Django 5.0.1 on 2024-07-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0013_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busca',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
