# Generated by Django 5.0.1 on 2024-07-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0014_alter_busca_nome_fantasia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busca',
            name='cd_cnae_principal',
        ),
        migrations.RemoveField(
            model_name='busca',
            name='cd_motivo_situacao_cadastral',
        ),
        migrations.AddField(
            model_name='busca',
            name='cnae_principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busca',
            name='motivo_situacao_cadastral',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
