# Generated by Django 5.0.1 on 2024-08-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0015_remove_busca_cd_cnae_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busca',
            name='vl_capital_social',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
