# Generated by Django 5.0.1 on 2024-08-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0016_busca_vl_capital_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busca',
            name='vl_capital_social',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
